name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 21 * * 0'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-java@v5
      with:
        java-version: 17
        distribution: temurin
    - uses: sbt/setup-sbt@6bec67c98f542b9e17369bfca0ec822ac1363194 # v1.1.19
    - uses: coursier/cache-action@v8
    - run: sbt "+ scalafmtCheckAll" scalafmtSbtCheck "+ test" "+ scripted"
